---
title: "Reproducible Research: Peer Assessment 1"
output:
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r, echo=TRUE}
require(ggplot2)
require(Hmisc)
require(plyr)
require(dplyr)

dat<-read.csv("activity.csv",colClasses="character")
dat$interval<-as.numeric(dat$interval)
dat$date<-as.Date(dat$date)
dat$steps<-as.numeric(dat$steps)

dat$time<-sapply(
  dat$interval,
  function(x) {
    H<-x%/%100 ;
    M<-x%%100 ;
    H<-sprintf("%02d", H) ;
    M<-sprintf("%02d", M) ;
    paste(c(H, ':', M), collapse='')
    }
  )

dat$Weekday<-weekdays(dat$date)
dat$Weekend<-ifelse((dat$Weekday == "Saturday") | (dat$Weekday == "Sunday"), "Weekend", "Weekday")

dat1<-dat[!is.na(dat$steps),]
```

## What is mean total number of steps taken per day?
```{r, echo=TRUE}
dat1<-group_by(dat1, date)
stepsDay<-summarise(dat1, totSteps=sum(steps))
qplot(totSteps, data=stepsDay, binwidth=5000)
mean(stepsDay$totSteps)
median(stepsDay$totSteps)
```


## What is the average daily activity pattern?
```{r, echo=TRUE}
dat1<-group_by(dat1, interval)
activityDay<-summarise(dat1, avgSteps=mean(steps))
qplot(interval, avgSteps, data=activityDay)+geom_line()+geom_smooth()
```



## Imputing missing values
```{r, echo=TRUE}
# http://stackoverflow.com/questions/9322773/how-to-replace-na-with-mean-by-subset-in-r-impute-with-plyr
datI <- ddply(dat, ~ interval, transform, steps = impute(steps, fun=mean))
datI <- datI[order(datI$date), ]
datI$steps <- round(as.numeric(datI$steps))

datI<-group_by(datI, date)
stepsDay<-summarise(datI, totSteps=sum(steps))
qplot(totSteps, data=stepsDay, binwidth=5000)
mean(stepsDay$totSteps)
median(stepsDay$totSteps)

datI<-group_by(datI, interval)
activityDayI<-summarise(datI, avgSteps=mean(steps))
qplot(interval, avgSteps, data=activityDayI)+geom_line()+geom_smooth()
```



## Are there differences in activity patterns between weekdays and weekends?
```{r, echo=TRUE}
dat1<-group_by(dat1, Weekend, interval)
activityWeekend<-summarise(dat1, avgSteps=mean(steps))
qplot(interval,avgSteps, color=Weekend, data=activityWeekend)+geom_line()+geom_smooth()
```


